version: "3.8"
services:
  postgres-customer:
    container_name: database-customer
    image: postgres
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: arman
      POSTGRES_PASSWORD: arman
      PGDATA: /data/postgres
    volumes:
      - postgres-customer:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring
      - postgres
    restart: unless-stopped

  postgres-order:
    container_name: database-order
    image: postgres
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: arman
      POSTGRES_PASSWORD: arman
      PGDATA: /data/postgres
    volumes:
      - postgres-order:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - spring
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  spring:
    driver: bridge
  postgres:
    driver: bridge
volumes:
  postgres-customer:
  postgres-order:
  pgadmin:
