version: "3.9"
services:
  postgres:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: "customer"
      POSTGRES_DB_order: "order"
      POSTGRES_USER: "arman"
      POSTGRES_PASSWORD: "arman"
      PGDATA: data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

  eureka-server:
    container_name: eureka-server
    image: 16ad/eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - spring
networks:
  spring:
    driver: bridge
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:
